language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '7.10'
before_script:
  - npm prune && npm cache clean
  - npm install
script:
  - npm run build && npm run test:prod
after_success:
  - ./scripts/upload-coverage.sh
  - ./scripts/gh-pages-publish.js

