language: node_js
branches:
  only:
    - master
    - /^greenkeeper/.*$/
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '7.10'
before_script:
  - npm install -g yarn
  - yarn cache clean
  - yarn install
script:
  - yarn test:prod
# after_success:
#  - npm run report-coverage
#  - npm run semantic-release
#  - npm run deploy-docs
